# Generated by Django 3.2.3 on 2021-05-20 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pontoturistico_atrcoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='atrcoes',
            new_name='atracoes',
        ),
    ]
