# Generated by Django 3.0.8 on 2021-05-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pontoturistico_avaliacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
