# Generated by Django 3.2.3 on 2021-05-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210527_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='dov_identificacao',
            new_name='doc_identificacao',
        ),
    ]
