# Generated by Django 3.2.3 on 2021-05-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0003_auto_20210524_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracao',
            name='observacoes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
